on: [push]
name: cabal-build
jobs:
  build:
    name: Build with Cabal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.6.0.0'
      - run: cabal build
